### ISSUE TITLE
Bootstrap 4 final is out

### ISSUE THREAD

**Issue by beckynet** [berkan52/select2-bootstrap4-theme#2]
Bootstrap 4 final is out
Please provide also scss to permit customise color or font.
Thanks for your work

**Comment by berkan52** [comment]
Hi, 

Firstly, i was updated for Bootstrap 4. 

If you want to change fonts and colors, change the bootstrap variable.sass file.

But in the next version maybe I can do what they say. At least I can get a more parametric version.

Thank you for usign this theme...
